### ISSUE TITLE
Help users know they need to provide contact information in descriptions

### ISSUE THREAD

**Issue by sethetter** [devict/job-board#30]
We have had a few postings recently that did not have a URL, and the description had no contact information.

I'm guessing the assumption is their email will be available for contact?

Maybe we give users a checkbox allowing their email to be displayed on the posting?

**Comment by kevinfalting** [comment]
Since the current email collection is for keeping spam down and providing a way to edit the post, I think it should remain the way it is. There's a good chance that the person managing the posting isn't necessarily the contact.

The simplest change would be to just add some description text next to the email, describing that it will be kept private and not displayed on the post. We could avoid a migration this way. Possibly adjust the Description input's ..._description_ as well.

Alternatively, we could add an optional contact input. Just a text box that can accept free-form contact info.

**Comment by cjprieb** [comment]
I'll take a look at adding this.

**Comment by cjprieb** [comment]
I plan to put this as the email description: "This email is kept private to allow you to edit the post and is not displayed publicly." Any suggestions for improvements?

**Comment by kevinfalting** [comment]
I think that's the simplest. Maybe include as a part of the description box to include contact info.
